global using AutoFixture;
global using OfficePerformanceReview.DomainTest.Common;
global using OfficeReview.Domain.Profile.Root;
global using OfficeReview.Domain.Questions.Root;
global using OfficeReview.Shared.SeedWork;
global using Bogus;
global using FluentAssertions;
global using OfficeReview.Domain.Profile.Enums;
global using System.Net.Mail;