global using OfficeReview.Domain.Questions.Entities;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Humanizer;
global using OfficePerformanceReview.Application.Repository;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.Extensions.Logging;
global using OfficeReview.Domain.Profile.Root;
global using OfficeReview.Shared.SeedWork;